name: Site lints

on:
  push:
    paths:
      - site/**/*.tsx
      - site/**/*.ts
      - site/yarn.lock

jobs:
  eslint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install
        working-directory: ./site

      - name: Run eslint
        run: npm run lint
        working-directory: ./site